server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none  # 서로 다른 도메인 간 쿠키 전송 허용
        secure: true     # HTTPS 환경에서만 쿠키 전송 (필수)
        http-only: true  # 자바스크립트로 쿠키 탈취 방지 (보안 강화)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/mutsa14_prod?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # 생성되는 SQL 쿼리를 로그로 확인
        format_sql: true

  web:
    error:
      include-message: always
      include-binding-errors: always

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}


coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  from-number: ${COOLSMS_FROM_NUMBER}

